### ISSUE TITLE
restoreLocalStorage doesn't wait for restore to complete

### ISSUE THREAD

**Issue by david-wb** [javierbrea/cypress-localstorage-commands#375] opened 2021-09-24 21:58 UTC
**Describe the bug**

There seems to be a delay between calling `cy.restoreLocalStorage()` and when the local storage values are fully restored.

We are having to put a `cy.wait()` after the restore to get around this issue which is not ideal. Shouldn't  `cy.restoreLocalStorage()` wait for the restore to be complete before returning?

**Comment by javierbrea** [comment] 2021-09-28 04:45
Hi @david-wb. Theoretically, the `restoreLocalStorage` command is synchronous, it doesn't make any async action. Note that you should call to `cy.reload` or `cy.visit` after calling it. If you are already doing it, please provide a code example in order to reproduce the issue.

**Comment by rkhomi** [comment] 2021-09-28 08:14
cy.reload and cy.visit after restoreLocalStorage?
your examples are luck of this information

**Comment by javierbrea** [comment] 2021-09-28 13:08
Sorry @rkhomi, you're right, it is not needed. I confused it with the `disableLocalStorage` command, which requires reloading. Could you please provide more information? What Cypress version are you using, an example of code, etc. As I told, restoring localStorage is synchronous, so it shouldn't produce async errors. Anyway, if it takes some time to be really restored in the browser, maybe we could convert it into an async command and perform some type of extra check before resolving it.

**Comment by javierbrea** [comment] 2022-07-22 12:56
Closed due to inactivity

**Closed by javierbrea** 2022-07-22 12:56 UTC
Labels: stage: needs information
